# Generated by Django 5.0.4 on 2024-09-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HE', 'Health'), ('FR', 'Friendship'), ('SU', 'Support')], default='HE', max_length=2)),
                ('text', models.TextField()),
                ('release_date', models.DateField(help_text='Monday of the week when announcement is released')),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('IN', 'In Review'), ('RE', 'Reviewed'), ('PU', 'Published')], default='DR', max_length=2)),
                ('published_on', models.DateTimeField(blank=True, help_text='Date and time of publication', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('release_date', models.DateField(help_text='Monday of the week when health tip is released')),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('IN', 'In Review'), ('RE', 'Reviewed'), ('PU', 'Published')], default='DR', max_length=2)),
                ('published_on', models.DateTimeField(blank=True, help_text='Date and time of publication', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('WE', 'Website'), ('ZO', 'Video Conference'), ('VI', 'Video'), ('FI', 'File')], default='WE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series_title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('HE', 'Health'), ('FR', 'Friendship'), ('SU', 'Support')], default='HE', max_length=2)),
                ('slug', models.SlugField(help_text='Append release date: slug-YY-MM-DD', max_length=200, unique_for_date='release_date')),
                ('release_date', models.DateField(help_text='Monday of the week when resource is released')),
                ('description', models.TextField()),
                ('art_uri', models.CharField(max_length=200, unique_for_date='release_date')),
                ('art_alt', models.CharField(max_length=200)),
                ('art_caption', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('IN', 'In Review'), ('RE', 'Reviewed'), ('PU', 'Published')], default='DR', max_length=200)),
                ('published_on', models.DateTimeField(blank=True, help_text='Date of publication', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wellness.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series_title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('HE', 'Health'), ('FR', 'Friendship'), ('SU', 'Support')], default='HE', max_length=2)),
                ('slug', models.SlugField(help_text='Append release date: slug-YY-MM-DD', max_length=200, unique_for_date='release_date')),
                ('release_date', models.DateField(help_text='Monday of the week when event is released')),
                ('description', models.TextField()),
                ('art_uri', models.CharField(max_length=200, unique_for_date='release_date')),
                ('art_alt', models.CharField(max_length=200)),
                ('art_caption', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('IN', 'In Review'), ('RE', 'Reviewed'), ('PU', 'Published')], default='DR', max_length=200)),
                ('published_on', models.DateTimeField(blank=True, help_text='Date of publication', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wellness.venue')),
            ],
        ),
    ]
