# Generated by Django 5.0.4 on 2024-09-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coppehr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='coppehr.venue'),
        ),
    ]
